services:
# ============================================
# Database service
# ============================================
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
# ============================================
# RabbitMQ service
# ============================================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
# ============================================
# Migration
# ============================================
  migration:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: migration
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    restart: "no"
# ============================================
# Prodaction service
# ============================================
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - migration
      - rabbitmq
    networks:
      - backend
      - public
# ============================================
# Prod distroless
# ============================================
  app-distroless:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod-distroless
    env_file:
      - .env
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    networks:
      - backend
      - public
# ============================================
# Create empty volumes
# ============================================
volumes:
  db-data: {}
  node_modules: {}
# ============================================
# Configure networks
# ============================================
networks:
  backend:
    driver: bridge
    # internal: true
  public:
    driver: bridge