services:
# ============================================
# Database service
# ============================================
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
# ============================================
# Migration
# ============================================
  migration:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: migration
    env_file:
      - .docker.env
    depends_on:
      - db
    networks:
      - backend
    restart: "no"
# ============================================
# Prodaction service
# ============================================
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    env_file:
      - .docker.env
    ports:
      - "8080:8080"
    depends_on:
      - migration
    networks:
      - backend
      - public
# ============================================
# Prod distroless
# ============================================
  app-distroless:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod-distroless
    env_file:
      - .docker.env
    ports:
      - "8081:8080"
    depends_on:
      - migration
    networks:
      - backend
      - public
# ============================================
# RabbitMQ service
# ============================================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: r_d_first_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
# ============================================
# Create empty volumes
# ============================================
volumes:
  db-data: {}
  node_modules: {}
# ============================================
# Configure networks
# ============================================
networks:
  backend:
    driver: bridge
    internal: true
  public:
    driver: bridge