# version: "3.9"
# ==============================================================================================
# Compose file to up application in dev mode with hot reload, bind-mount and quick iteration
# ==============================================================================================
# Database Service
# ==============================================================================================
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
# =============================================================================================
# Dev mode
# =============================================================================================
  app:
    working_dir: /usr/app
    volumes:
      - .:/usr/app  # bind-mount
      - node_modules:/usr/app/node_modules  # to make node_modules stable
    ports:
      - "8080:8080"
    env_file:
      - .docker.env
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    depends_on:
      - db
    networks:
      - backend
    # To run dev stage via docker-compose
    build:
      context: .
      dockerfile: Dockerfile.dev
# ============================================
# RabbitMQ service
# ============================================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: r_d_first_rabbitmq_dev
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  # Define db-data
volumes:
  db-data: {}
  node_modules: {}
# ============================================
# Configure networks
# ============================================
networks:
  backend:
    driver: bridge