# syntax=docker/dockerfile:1
# Define global node version variable
ARG NODE_VERSION=22.19.0
FROM node:${NODE_VERSION}-alpine
# Define working directory
WORKDIR /usr/app
# Install all dependecies including dev
COPY ./package*.json ./

# Copy environment variables
COPY .docker.env ./

RUN npm install
# Copy source ..
CMD ["npm", "run", "start:dev"]